apiVersion: v1
kind: Service
metadata:
  name: {{ include "devedge-redis.fullname" . }}
  labels:
    {{- include "devedge-redis.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "devedge-redis.selectorLabels" . | nindent 4 }}
  ports:
    - name: redis
      port: {{ .Values.port }}
      targetPort: redis
      protocol: TCP
