// Package makefrag generates and inspects the managed Makefile fragment that
// `de sync` writes (WS-023).
//
// The fragment lives at .devedge/make/devedge.mk and contains nothing but
// one-line targets that delegate to `de`, the hermetic build authority. The
// build LOGIC lives in `de`, not in the Makefile, so the fragment's behavior
// cannot drift on tool versions; only the SET of targets changes, and `de sync`
// regenerates it idempotently. A project's top-level Makefile is hand-owned and
// simply reads this fragment:
//
//	-include .devedge/make/devedge.mk
//	# project-specific targets below
package makefrag

import (
	"bytes"
	"path/filepath"
)

// RelPath is the fragment's path relative to the project root.
const RelPath = ".devedge/make/devedge.mk"

// header marks the file as generated. `de doctor` uses it to recognise a
// managed fragment; its presence plus a content mismatch means "hand-edited".
const header = "# Code generated by `de sync`. DO NOT EDIT."

// content is the canonical fragment body. Each target delegates to a `de` verb,
// so the recipe is a one-liner and the logic stays central. `migrate-lint`
// delegates to WS-022's `de migrate lint`.
const content = header + `
#
# Managed build shim written by ` + "`de sync`" + ` (WS-023). Every target delegates
# to ` + "`de`" + `, the hermetic build authority — so the recipe cannot drift on tool
# versions. Do NOT edit; re-run ` + "`de sync`" + ` to regenerate. Your top-level
# Makefile should be hand-owned and just read this fragment:
#
#     -include .devedge/make/devedge.mk
#     # project-specific targets below
#
.PHONY: generate build test lint image migrate-lint

generate: ; @de generate
build:    ; @de build
test:     ; @de test
lint:     ; @de lint
image:    ; @de image
migrate-lint: ; @de migrate lint
`

// Content returns the canonical managed-fragment bytes `de sync` writes.
func Content() []byte { return []byte(content) }

// Path returns the absolute (or root-relative) fragment path for a project root.
func Path(root string) string { return filepath.Join(root, RelPath) }

// IsManaged reports whether b looks like a `de sync` fragment (has the header).
// A file that lacks the header is treated as user-owned and left untouched.
func IsManaged(b []byte) bool {
	return bytes.HasPrefix(bytes.TrimLeft(b, " \t\r\n"), []byte(header))
}

// IsCurrent reports whether b is byte-identical to the canonical fragment.
// A managed fragment that is not current is stale or hand-edited.
func IsCurrent(b []byte) bool { return bytes.Equal(b, Content()) }
