package makefrag

import (
	"bytes"
	"strings"
	"testing"
)

func TestContent_HeaderAndTargets(t *testing.T) {
	got := string(Content())
	if !strings.HasPrefix(got, "# Code generated by `de sync`. DO NOT EDIT.") {
		t.Fatalf("fragment must start with the DO NOT EDIT header, got:\n%s", got)
	}
	// Every build verb must be a one-line target delegating to `de`.
	for _, want := range []string{
		"generate: ; @de generate",
		"build:    ; @de build",
		"test:     ; @de test",
		"lint:     ; @de lint",
		"image:    ; @de image",
		"migrate-lint: ; @de migrate lint",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("fragment missing target line %q", want)
		}
	}
}

func TestIsManaged(t *testing.T) {
	if !IsManaged(Content()) {
		t.Error("canonical fragment must be recognized as managed")
	}
	if IsManaged([]byte("test:\n\tgo test ./...\n")) {
		t.Error("a hand-written Makefile must not be recognized as managed")
	}
	// Leading whitespace before the header is tolerated.
	if !IsManaged(append([]byte("\n\n"), Content()...)) {
		t.Error("leading blank lines should not defeat header detection")
	}
}

func TestIsCurrent(t *testing.T) {
	if !IsCurrent(Content()) {
		t.Error("canonical fragment must be current")
	}
	// A managed-but-edited fragment is not current (doctor should flag it).
	edited := bytes.Replace(Content(), []byte("@de test"), []byte("@echo hacked"), 1)
	if IsCurrent(edited) {
		t.Error("hand-edited managed fragment must not be reported as current")
	}
}
