package compose

import (
	"fmt"
	"sort"
	"strings"

	"github.com/infobloxopen/devedge/pkg/config"
)

// SDKVersion is the devedge-sdk version the generated composed binary requires.
// It is the version devedge itself is built against (WS-012 P4 consumes v0.28.0).
// Keep it in sync with the require in devedge's go.mod when the SDK is bumped.
const SDKVersion = "v0.28.0"

// GeneratedFiles is the output of Generate: the rendered, ready-to-write files
// for a composed binary (paths are relative to the composition's project dir).
type GeneratedFiles struct {
	// MainGo is cmd/<name>/main.go — the host entrypoint importing the modules.
	MainGo string
	// GoMod is cmd/<name>/go.mod — the composed binary's module file.
	GoMod string
	// Lock is cmd/<name>/composition.lock — the pinned member/SDK/toolchain set.
	Lock string
	// Dir is the relative output directory ("cmd/<name>").
	Dir string
}

// Generate renders the composed-binary sources for a composition. It is pure (no
// I/O) so it is trivially testable; the cobra command writes the result.
//
// goVersion is the Go toolchain version line for the generated go.mod (e.g.
// "1.26.0"); modulePath is the Go module path of the generated binary (e.g.
// "github.com/acme/control-plane/cmd/control-plane").
func Generate(c *config.Composition, goVersion, modulePath string) (GeneratedFiles, error) {
	refs, err := ResolveModuleRefs(c)
	if err != nil {
		return GeneratedFiles{}, err
	}
	name := c.Project()
	dir := "cmd/" + name
	return GeneratedFiles{
		MainGo: renderMainGo(c, refs),
		GoMod:  renderGoMod(modulePath, goVersion, refs),
		Lock:   renderLock(c, refs, goVersion),
		Dir:    dir,
	}, nil
}

// renderMainGo renders cmd/<name>/main.go: it imports each member module package
// and calls servicekit.Run with a HostConfig built from the composition spec —
// STATIC composition (the modules are imported, not loaded as plugins).
func renderMainGo(c *config.Composition, refs []ModuleRef) string {
	var b strings.Builder
	b.WriteString("// Code generated by `de compose build`; DO NOT EDIT.\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "// Composed host for %q (WS-012). It IMPORTS the member service modules and\n", c.Project())
	b.WriteString("// runs them in ONE process via servicekit.Run — static composition, no Go\n")
	b.WriteString("// plugins. Regenerate after editing the composition (do not hand-edit).\n")
	b.WriteString("package main\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"log\"\n\n")
	b.WriteString("\t\"github.com/infobloxopen/devedge-sdk/servicekit\"\n")
	for _, r := range refs {
		fmt.Fprintf(&b, "\t%s %q\n", r.Alias, r.ImportPath)
	}
	b.WriteString(")\n\n")

	b.WriteString("func main() {\n")
	b.WriteString("\thc := servicekit.HostConfig{\n")
	b.WriteString("\t\tModules: []servicekit.Module{\n")
	for _, r := range refs {
		fmt.Fprintf(&b, "\t\t\t%s.Module(),\n", r.Alias)
	}
	b.WriteString("\t\t},\n")

	if g := c.Spec.Runtime.GRPC; g != "" {
		fmt.Fprintf(&b, "\t\tGRPCAddr: %q,\n", g)
	}
	if h := c.Spec.Runtime.HTTP; h != "" {
		fmt.Fprintf(&b, "\t\tHTTPAddr: %q,\n", h)
	}

	if d := c.Spec.Database; d != nil {
		b.WriteString("\t\tDatabase: &servicekit.DatabaseConfig{\n")
		fmt.Fprintf(&b, "\t\t\tEngine: %q,\n", d.Engine)
		if d.Isolation != "" {
			fmt.Fprintf(&b, "\t\t\tDefaultIsolation: servicekit.IsolationPolicy(%q),\n", d.Isolation)
		}
		b.WriteString("\t\t},\n")
	}

	// Per-module failure policies (proposal §5.9), emitted only when any module
	// declares one. Keyed by module name, deterministically ordered.
	policies := map[string]string{}
	for _, m := range c.Spec.Modules {
		if m.FailurePolicy != "" {
			policies[m.Name] = m.FailurePolicy
		}
	}
	if len(policies) > 0 {
		b.WriteString("\t\tFailurePolicies: map[string]servicekit.FailurePolicy{\n")
		names := make([]string, 0, len(policies))
		for n := range policies {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			fmt.Fprintf(&b, "\t\t\t%q: servicekit.FailurePolicy(%q),\n", n, policies[n])
		}
		b.WriteString("\t\t},\n")
	}

	b.WriteString("\t}\n")
	b.WriteString("\tif err := servicekit.Run(hc); err != nil {\n")
	b.WriteString("\t\tlog.Fatal(err)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// renderGoMod renders the composed binary's go.mod: its module path, Go version,
// and a require for the SDK plus each pinned member module's enclosing module.
// Member requires use the module's import path with its pinned version; an
// unpinned member is required at "latest" (the lock records the gap).
func renderGoMod(modulePath, goVersion string, refs []ModuleRef) string {
	var b strings.Builder
	fmt.Fprintf(&b, "module %s\n\n", modulePath)
	fmt.Fprintf(&b, "go %s\n\n", goVersion)
	b.WriteString("require (\n")
	fmt.Fprintf(&b, "\tgithub.com/infobloxopen/devedge-sdk %s\n", SDKVersion)
	// Deduplicate by import path; the same enclosing module may host >1 member.
	seen := map[string]struct{}{}
	for _, r := range refs {
		if _, dup := seen[r.ImportPath]; dup {
			continue
		}
		seen[r.ImportPath] = struct{}{}
		ver := r.Version
		if ver == "" {
			ver = "latest"
		}
		fmt.Fprintf(&b, "\t%s %s\n", r.ImportPath, ver)
	}
	b.WriteString(")\n")
	return b.String()
}
