package compose

import (
	"fmt"
	"strings"

	"github.com/infobloxopen/devedge/pkg/config"
	"gopkg.in/yaml.v3"
)

// LockVersion is the composition.lock schema version. Bump when the lock shape
// changes incompatibly.
const LockVersion = "v1"

// Lock is the pinned, reproducible-build manifest a `de compose build` emits next
// to the generated main.go (proposal §6.2; §11 risk "module/SDK skew"). It pins
// each member module's resolved version plus the SDK + Go toolchain, and carries
// per-member codegen/proto/migration provenance slots so a rebuild reproduces the
// exact composed binary.
type Lock struct {
	// LockVersion is the lock schema version (LockVersion).
	LockVersion string `yaml:"lockVersion"`
	// Composition is the composition name the lock pins.
	Composition string `yaml:"composition"`
	// SDK is the devedge-sdk version the composed binary is built against.
	SDK string `yaml:"sdk"`
	// Go is the Go toolchain version line.
	Go string `yaml:"go"`
	// Modules are the pinned member modules, in composition order.
	Modules []LockModule `yaml:"modules"`
}

// LockModule pins one member module's resolved version + its provenance.
type LockModule struct {
	// Name is the member's short name (ModuleEntry.Name).
	Name string `yaml:"name"`
	// Module is the member's import path.
	Module string `yaml:"module"`
	// Version is the pinned version, or "" when the composition left it floating
	// (recorded so `de compose tidy` can flag the gap).
	Version string `yaml:"version"`
	// Codegen, Proto, Migration are provenance slots for the toolchain versions
	// the member's generated code, proto contract, and migrations were produced
	// with. They are populated from the member descriptor's Requires/Version when
	// available and left empty otherwise (a future-proofing seam, not invented data).
	Codegen   string `yaml:"codegen,omitempty"`
	Proto     string `yaml:"proto,omitempty"`
	Migration string `yaml:"migration,omitempty"`
}

// BuildLock assembles the Lock for a composition + its resolved member refs.
func BuildLock(c *config.Composition, refs []ModuleRef, goVersion string) Lock {
	mods := make([]LockModule, 0, len(refs))
	for _, r := range refs {
		mods = append(mods, LockModule{
			Name:    r.Name,
			Module:  r.ImportPath,
			Version: r.Version,
		})
	}
	return Lock{
		LockVersion: LockVersion,
		Composition: c.Project(),
		SDK:         SDKVersion,
		Go:          goVersion,
		Modules:     mods,
	}
}

// renderLock renders the composition.lock YAML for a composition. Pure (no I/O).
func renderLock(c *config.Composition, refs []ModuleRef, goVersion string) string {
	lock := BuildLock(c, refs, goVersion)
	var b strings.Builder
	b.WriteString("# composition.lock — generated by `de compose build`; pins the composed\n")
	b.WriteString("# binary's member modules + SDK + toolchain for reproducible builds (WS-012).\n")
	b.WriteString("# Regenerate with `de compose build`; do not hand-edit.\n")
	data, err := yaml.Marshal(lock)
	if err != nil {
		// yaml.Marshal of this plain struct cannot fail in practice; fall back to
		// a minimal valid doc rather than panicking in a generator.
		return fmt.Sprintf("lockVersion: %s\ncomposition: %s\n", LockVersion, c.Project())
	}
	b.Write(data)
	return b.String()
}
